name: test-all-example
on: [push]
jobs:
  test-all:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: '15'
    - run: npm ci
    - run: npm run test-all