name: test-projects-example
on: [workflow_dispatch]
jobs:
  test-projects:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: '15'
    - run: npm ci
    - run: npm run test:projects